CREATE TABLE IF NOT EXISTS film
(
    "id"           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name"         varchar(100),
    "description"  varchar(254),
    "release_date" date,
    "duration"     int,
    "mpa_id"       bigint
);

CREATE TABLE IF NOT EXISTS "user"
(
    "id"       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "email"    varchar(50),
    "login"    varchar(50) NOT NULL UNIQUE,
    "name"     varchar(50),
    "birthday" date
);

CREATE TABLE IF NOT EXISTS user_friends
(
    "user_id"   bigint,
    "friend_id" bigint,
    "agree"     boolean,
    PRIMARY KEY ("user_id", "friend_id")
);

CREATE TABLE IF NOT EXISTS film_likes
(
    "user_id" bigint,
    "film_id" bigint,
    PRIMARY KEY ("user_id", "film_id")
);

CREATE TABLE IF NOT EXISTS film_genres
(
    "film_id"  bigint,
    "genre_id" bigint,
    PRIMARY KEY ("film_id", "genre_id")
);

CREATE TABLE IF NOT EXISTS genre
(
    "id"   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" varchar(50)
);

CREATE TABLE IF NOT EXISTS mpa
(
    "id"   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" varchar(50)
);

ALTER TABLE film
    ADD FOREIGN KEY ("mpa_id") REFERENCES mpa ("id");

ALTER TABLE user_friends
    ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id");

ALTER TABLE user_friends
    ADD FOREIGN KEY ("friend_id") REFERENCES "user" ("id");

ALTER TABLE film_likes
    ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id");

ALTER TABLE film_likes
    ADD FOREIGN KEY ("film_id") REFERENCES film ("id");

ALTER TABLE film_genres
    ADD FOREIGN KEY ("film_id") REFERENCES film ("id");

ALTER TABLE film_genres
    ADD FOREIGN KEY ("genre_id") REFERENCES genre ("id");
